from django.core.exceptions import ValidationError

def validate_information(data):
    return data
